### ISSUE TITLE
[REQUEST] Roadmap

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#16]
It seems that many users don't know where to find information about the roadmap.
So it could be a good idea to promote regularly the [roadmap page](https://developer.joomla.org/roadmap.html) on the dev site.

- [ ] Facebook fan page (Sigrid)
- [ ] Google+ (Alison)
- [ ] Twitter Dev / retweet on J! (Sandra)
- [ ] Instagram (Sandra)
- [ ] LinkedIn (Hans, Alison)
- [ ] Pinterest (Sigrid)
- [ ] Facebook group (Alison)

Facebook
![roadmap-facebook](https://user-images.githubusercontent.com/4682328/27764485-8d37672e-5e68-11e7-965e-da2543d19bac.png)

Instagram
![roadmap-instagram](https://user-images.githubusercontent.com/4682328/27764487-8eae6170-5e68-11e7-8087-5de1352daa0b.png)

Twitter (I will tweet it a day or another on the dev account) 
![roadmap-twitter](https://user-images.githubusercontent.com/4682328/27764484-8bb72268-5e68-11e7-80d5-ff62e81529cc.png)

**Comment by Sandra97** [comment]
Please check when done:
- [ ] Facebook fan page (Sigrid)
- [ ] Google+ (Alison)
- [ ] Twitter Dev / retweet on J! (Sandra)
- [ ] Instagram (Sandra)
- [ ] LinkedIn (Hans, Alison)
- [ ] Pinterest (Sigrid)
- [ ] Facebook group (Alison)

**Comment by Sandra97** [comment]
Posted on Twitter/Facebook on August 23rd, 2017.

**Comment by Sandra97** [comment]
Merged to Glip tasks.
